### ISSUE TITLE
testerConnexion336urls test failed

### ISSUE THREAD

**Issue by koitrinkoffi** [koitrinkoffi/PDL_2019-2020_GR5#1]
After test running with `mvn test` one test case failed.
output of this error : **at com.wikipediaMatrix.UrlTest.testerConnexion336Urls(UrlTest.java:134)**.

So i decide to ignore with a `@Ignore` in my last commit but we have to resolve this

@Wizo17 @Laeba @kouassives @NguyenAnhCu

**Comment by koitrinkoffi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Repartition du code](https://trello.com/c/sKEtE3Ex/6-repartition-du-code)

**Comment by kouassives** [comment]
There are **two more URLs** that do not have an article. However, these URLs were **not counted** in the test cases.
So, we have 312 URLs that have an article and 24 URLs that do not have an article.
**the lines to modify:**
       

> assertEquals(articleExistant, 314); 
> assertEquals(articleInexistant, 22);
> System.out.println("URLs sans article : " + articleExistant);

to

> assertEquals(articleExistant, **312**); 
> assertEquals(articleInexistant, **24**);
> System.out.println("URLs sans article : " + **articleInexistant**);

**Comment by kouassives** [comment]
There are **two more URLs** that do not have an article. However, these URLs were **not counted** in the test cases.
So, we have 312 URLs that have an article and 24 URLs that do not have an article.
**the lines to modify:**
       

> assertEquals(articleExistant, 314); 
> assertEquals(articleInexistant, 22);
> System.out.println("URLs sans article : " + articleExistant);

to

> assertEquals(articleExistant, **312**); 
> assertEquals(articleInexistant, **24**);
> System.out.println("URLs sans article : " + **articleInexistant**);
