### ISSUE TITLE
Tests & extractions display "null"

### ISSUE THREAD

**Issue by Laeba** [koitrinkoffi/PDL_2019-2020_GR5#10]
When a page does not contains any table, it pops up a "null" message

**Comment by Wizo17** [comment]
Exceptions are now captured when an extraction fails.
[link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/8801e358aec8713dffceb9a409e503a6dc75d997#diff-d943cec7aa5114c07a1aab9b53f71cc3R156-R165)
