### ISSUE TITLE
Method does not work properly Donnee_Html.stockerCellule(Element cellule)

### ISSUE THREAD

**Issue by kouassives** [koitrinkoffi/PDL_2019-2020_GR5#12]
While creating a new cell, the method skips the reserved cells. And an exception is raised for the url **https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units**. This url contains a _very structured_ table so it is difficult to place the cells in the right position

> It should be ensured that when skipping the cells, the size of the table is not exceeded

**Comment by Wizo17** [comment]
We can extract both simple and non-interleaved tables. However for some arrays the 'jsoup' library does not allow us to browse the html correctly. 
[link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/3a6893b3c017254cdabe73b5b5aab7dbfc8e47c1)
