### ISSUE TITLE
Wikitable extractor does not work

### ISSUE THREAD

**Issue by Wizo17** [koitrinkoffi/PDL_2019-2020_GR5#14]
In more than 80% of cases csv obtained with `Donnee_wikitable` are not good.

**Comment by koitrinkoffi** [comment]
Yes that is right, we need a csv validator but I think that it is an another feature which should be implemented.

**Comment by koitrinkoffi** [comment]
I wrote a test case to show this issue you can find at [link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/caf420571b5793972dab8c48bac347ce70e165c6#diff-91955fd7dd3382181f8d749609219e15R92-R106)

**Comment by kouassives** [comment]
This issue can be closed with this [Link](url)
