### ISSUE TITLE
Unstructured CSV does not allow to validate CSV

### ISSUE THREAD

**Issue by Laeba** [koitrinkoffi/PDL_2019-2020_GR5#15]
During the validation of the CSV, the API brings up an error as "string index out of range". In fact, there is a ";" at the end of every lines which makes it a bad structure.

**Comment by koitrinkoffi** [comment]
Yes, this right you can see this issue with this test case [link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/caf420571b5793972dab8c48bac347ce70e165c6#diff-91955fd7dd3382181f8d749609219e15R108-R122) don't forget to read **Comparison_between_U.S._states_and_countries_by_GDP_(PPP)-01.csv** file after this test to see with more details.

**Comment by Wizo17** [comment]
I fixed some functions to fix the bug with";" at the end of the csv for simple tables. [link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/9cfabec02f9f60181115aae1a21384845fe40f73)

**Comment by Wizo17** [comment]
We have fixed the wrong addition of ';' to the CSV by creating a single method that should do it. 
 [link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/3a6893b3c017254cdabe73b5b5aab7dbfc8e47c1#diff-d943cec7aa5114c07a1aab9b53f71cc3R230-R238)
