### ISSUE TITLE
Method "pageComporteTableau()" does not work properly

### ISSUE THREAD

**Issue by Wizo17** [koitrinkoffi/PDL_2019-2020_GR5#4]
For the same Wikipedia page, the function **`pageComporteTableau()`** for classes `Donnee_html` and `Donnee_wikitable` does not always return the same value.

**Comment by koitrinkoffi** [comment]
I found another problem, you can see that with my next commit

**Comment by koitrinkoffi** [comment]
Finally this method work correctly
