### ISSUE TITLE
com.wikipediaMatrix.Donnee.recupContenu throws ExtractionInvalideException

### ISSUE THREAD

**Issue by Wizo17** [koitrinkoffi/PDL_2019-2020_GR5#5]
For the same Wikipedia page, the function **`getNbTableaux()`** for classes `Donnee_html` and `Donnee_wikitable` does not always return the same value.

**Comment by koitrinkoffi** [comment]
I wrote a test case but I get an exception **ExtractionInvalideException** in `Donnee.java:158` before, so I redirect this issue to **com.wikipediaMatrix.Donnee.recupContenu throws ExtractionInvalideException** . you can find the tests which show that at [link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/blob/develop/src/test/java/com/wikipediaMatrix/ApplicationTest.java#L42-L61)

**Comment by koitrinkoffi** [comment]
I resolve the **ExtractionInvalideException** you can find it in this commit [link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/d1bbce0c31306842c231ec7da6a5ec8d491bad6e) but the two extractor don't extract the same number of table in a same wikipage. You can find this test at [link](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/caf420571b5793972dab8c48bac347ce70e165c6#diff-91955fd7dd3382181f8d749609219e15R72-R90)

**Comment by kouassives** [comment]
This issue can be closed with this [Link](url)
