### ISSUE TITLE
When a table contains a Json format

### ISSUE THREAD

**Issue by Laeba** [koitrinkoffi/PDL_2019-2020_GR5#6]
The `extraire()` method in the `Donnees_Wikitable` Class does not work properly, in fact whenever a table contains a json format it makes the extractors crash.

**Comment by Laeba** [comment]
A test was made to prove this case, the method is called "verifierJson", you can find it in WikiExtractMainTest class.

**Comment by koitrinkoffi** [comment]
@Laeba can you put a link to give us an acces to this test case in your commit ?

**Comment by kouassives** [comment]
This issue can be closed with this [Link](url)
