### ISSUE TITLE
method Donnee.getNbLignesAjouteesRowspans(Elements rowspans) does not work properly

### ISSUE THREAD

**Issue by NguyenAnhCu** [koitrinkoffi/PDL_2019-2020_GR5#8]
it throws exception : java.lang.NumberFormatException: For input string: "31" " 
org.jsoup.select.Elements.attr(String agrs) causing this error by bring bad string format with syntax ". For example: "31" "

**Comment by kouassives** [comment]
To solve this bug, I added to the method **Donnee.getNbLignesAjouteesRowspans(Elements rowspans)** a method for checking the data _"`rowspan`"_ by **Elements.attr (String attributeKey)**, in order to retrieve the correct number of rows added by the rowspans for an extracted table.

> The existence of this error has been proved during the coverage. It was caused by a coding error. The old code did not check the quality of the data (the values ​​of the tags of the web page) before using it

**Comment by kouassives** [comment]
to see the test that proves this bug clic [here](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commits/develop#diff-91955fd7dd3382181f8d749609219e15R130-R160)

**Comment by kouassives** [comment]
To see the solution clik [here](https://github.com/koitrinkoffi/PDL_2019-2020_GR5/commit/6e0609228c0b504db8a9c6b28c4bcde8be5c2164#diff-3df70f03333e0f1f81c520f8a6c4a437R105)
